name: manganarrator_video

render:
  fps: 24
  size: [1280, 720]
  crossfade_s: 0.5
  vcodec: h264_nvenc
  cq: 23
  nvenc_preset: p5
  nvenc_tune: hq
  pix_fmt: yuv420p
  max_height: 4096

paths:
  input_images: input/images
  input_audio: input/audio
  output_dir: output
