name: manganarrator_video

clips:
  - image: "inputs/scene1.png"
    audio: "inputs/scene1.wav"
    fps: 24
    max_h: 1080
    max_w: 1920
    loop: 1
    pix_fmt: "yuv420p"
    sar: 1
  - image: "inputs/scene2.png"
    audio: "inputs/scene2.wav"
    fps: 24
    max_h: 1080
    loop: 1

render:
  out_path: "outputs/final_video.mp4"
  fps: 30
  vcodec: "h264_nvenc"
  cq: 23
  preset: "p5"
  tune: "hq"
  pix_fmt: "yuv420p"
  fade_s: 0.5
  transition: "fade"
  audio_fade: "acrossfade"
  overwrite: true
  verbose: true
