name: manganarrator_video

out_path: "outputs/final_video.mp4"
fps: 30
vcodec: "h264_nvenc"
cq: 23
preset: "p5"
tune: "hq"
pix_fmt: "yuv420p"
fade_s: 0.5
transition: "fade"
audio_fade: "acrossfade"
overwrite: true
verbose: true
